export const CALL_API= 'CALL_API';

export const apiExecutionState = {
  STARTED: '_STARTED',
  FINISHED: '_FINISHED',
  ERROR: '_ERROR'
};

export const userActionTypes = {
  API_USER_LOGIN: 'API_USER_LOGIN',
};

export const boardActionTypes = {
  API_GET_ALL_BOARDS: 'API_GET_ALL_BOARDS',
  API_GET_ALL_BOARDS_LOOKUP: 'API_GET_ALL_BOARDS_LOOKUP',
  API_CREATE_BOARD: 'API_CREATE_BOARD',
  API_DELETE_BOARD: 'API_DELETE_BOARD',
  API_UPDATE_BOARD: 'API_UPDATE_BOARD'
};

export const standardActionTypes = {
  API_GET_ALL_STANDARDS: 'API_GET_ALL_STANDARDS',
  API_CREATE_STANDARD: 'API_CREATE_STANDARD',
  API_DELETE_STANDARD: 'API_DELETE_STANDARD',
  API_UPDATE_STANDARD: 'API_UPDATE_STANDARD'
};

